### ISSUE TITLE
ServiceNotUpError: Service 'OneService' is not running.*

### ISSUE THREAD

**Issue by eileenfan** [bailuk/AAT#15]
//package name: ch.bailu.aat
//version: v1.7-beta
//target sdk version: android-18
 ch.bailu.aat.services.ServiceLink$ServiceNotUpError: Service 'OneService' is not running.*
 	at ch.bailu.aat.services.ServiceLink.getService(ServiceLink.java:137)
 	at ch.bailu.aat.services.ServiceLink.getTrackerService(ServiceLink.java:183)
 	at ch.bailu.aat.menus.OptionsMenu.prepare(OptionsMenu.java:63)
 	at ch.bailu.aat.activities.AbsMenu.onPrepareOptionsMenu(AbsMenu.java:32)
 	at android.app.Activity.onPreparePanel(Activity.java:2522)
 	at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:441)
 	at com.android.internal.policy.impl.PhoneWindow.onKeyDownPanel(PhoneWindow.java:795)
 	at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1471)
 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1867)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3791)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3516)
 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3666)
 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:1982)
 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1698)
 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1689)
 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1959)
 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
 	at android.os.MessageQueue.nativePollOnce(Native Method)
 	at android.os.MessageQueue.next(MessageQueue.java:132)
 	at android.os.Looper.loop(Looper.java:124)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by bailuk** [comment]
Current version is v1.9-beta please only send bug reports related to the latest release.

This happens when you open the Options Menu. How do you open the Options Menu? On what Android Version? On what phone? Also can you reproduce this on the latest release?

**Comment by bailuk** [comment]
This is probably fixed by now
