### ISSUE TITLE
MapFileException: file does not exist: /storage/C973-F26F/maps/berlin.map

### ISSUE THREAD

**Issue by eileenfan** [bailuk/AAT#16]
//package name: ch.bailu.aat
//version: v1.6-beta
//target sdk version: android-18
 java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.bailu.aat.debug/ch.bailu.aat.activities.TestActivity}: org.mapsforge.map.reader.header.MapFileException: file does not exist: /storage/C973-F26F/maps/berlin.map
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: org.mapsforge.map.reader.header.MapFileException: file does not exist: /storage/C973-F26F/maps/berlin.map
 	at org.mapsforge.map.reader.MapFile.<init>(MapFile.java:245)
 	at org.mapsforge.map.reader.MapFile.<init>(MapFile.java:207)
 	at ch.bailu.aat.activities.TestActivity.createMultiView(TestActivity.java:172)
 	at ch.bailu.aat.activities.TestActivity.onCreate(TestActivity.java:86)
 	at android.app.Activity.performCreate(Activity.java:5133)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)

**Comment by bailuk** [comment]
Current version is _v1.9-beta_ please only send bug reports related to the latest release.

This happened when you started _TestActivity_ in the _debug release_. TestActivity is only for testing and is not granted to work.

**Comment by bailuk** [comment]
Not relevant anymore
